name: deploy
on:
  push:
    branches:
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t romanhudyma/idp-deploy-next .
      - name: sign in to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASS }}'
      - name: push to docker hub
        run: docker push romanhudyma/idp-deploy-next:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker hub
        run: docker pull romanhudyma/idp-deploy-next:latest
      - name: clean up prev container
        run: docker rm -f idp-deploy-container-next
      - name: run container
        run: docker run -d -p 3000:3000 --name idp-deploy-container-next romanhudyma/idp-deploy-next