name: deploy
on:
  push:
    branches:
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t romanhudyma/idp-deploy-next .
      - name: sign in to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASS }}'
      - name: push to docker hub
        run: docker push romanhudyma/idp-deploy-next:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
      - name: deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_NEXT }} << 'EOF'
            docker pull romanhudyma/idp-deploy-next:latest
            docker rm -f idp-deploy-container-next || true
            docker run -d -p 3000:3000 --name idp-deploy-container-next romanhudyma/idp-deploy-next
          EOF